### PR TITLE
Search

### PR DESCRIPTION
**Pull request by gbonfant**
Hello!

I came across this project through 24pullrequests and as someone who's looking to contribute more to open source I think it's a fantastic initiative :bowtie:

The PR is for issue #16 and it is still a WIP since I'm not sure what kind of search we'd like to have – For the time being is a simple `Project` search over `owner` and `name`, also there's no front-end to speak of. Since there's already a search box-like element in the navbar I kept wondering where to put a search bar. Where do you think we could fit this? (sidebar comes to mind).

Finally I'd like to get some feedback on the code style/approach before continuing on.

Cheers!

### CODE REVIEW

**Comment by andrew** [comment]
Hi @gbonfant and welcome to the project, this is looking great!

I think it would be neat to have the current text box in the navbar to become a kind of combo search/add field, if someone puts in a full github url, i.e. `https://github.com/andrew/contribulator` or `andrew/contribulator` it should redirect the user to that project page, and download the information for it if it's not already in the database, otherwise it should do a search using what ever was entered.

Does that make sense? 

It would also be good to search against project descriptions and allow filtering/faceting of search results by `main_language`, not sure how easy that is to do with pg_search?

Your coding style looks fine, I tend to use https://github.com/bbatsov/rubocop to make small suggestions like preferring `'` over `"` for strings without interpolation but I'm not that fussy over it.

Give me a shout if you need anything and when this is ready for review and then we can roll it out to heroku :shipit: 

Thanks again for getting involved!

**Comment by gbonfant** [comment]
Thank you!

Ah yes, I like the sound of a combo field, also filtering/faceting can be done with `pg_search` – I'll let you know once is ready for review.

**Comment by gbonfant** [comment]
Hey @andrew would you mind taking a look at the latest version? It adds both the combo search/add and filtering by language.

I didn't quite know what to do with the UI so I implemented a sort of placeholder filtering – It does the job but it's not great, any thoughts on that?

**Comment by andrew** [comment]
@gbonfant looks like that last commit broke the test suite, I'll pull this down and have a look later today, some nice refactoring in here too by the looks of things :+1:

**Comment by gbonfant** [comment]
Ha! Good to see the tests I wrote are working :) – I did a little of refactoring as the `Project` model was growing a bit unwieldily. I'd like to also clean up the `create` action but perhaps that's for another PR

**Comment by andrew** [comment]
@gbonfant is there a rake task I need to run to index the documents?

**Comment by gbonfant** [comment]
Hey @andrew, there shouldn't since the search is done against one AR instance – It should literally work out of the box, are you having any issues?

**Comment by andrew** [comment]
Ah ha, no you're right it does just work, I'm just so used to using elasticsearch and having to reindex it. It's looking good to me, I'll have another play tomorrow morning and merge it then!

**Comment by andrew** [comment]
Sorry for the delay @gbonfant, I'm going to :ship: it now!

**Comment by gbonfant** [comment]
:fireworks:

**Pull request merged**
