### PR TITLE
Add spec for ScoreCalculator

### PR DESCRIPTION
**Pull request by wadtech**
Add a simple spec for the ScoreCalculator to pave the way for #59 and any other changes to the scoring that might be required.

### CODE REVIEW

**Comment by wadtech** [comment]
Also closes #55 and updates the #commits_since method to actually use a date in its call.

**Comment by andrew** [comment]
Very nice work @wadtech :+1:

**Comment by wadtech** [comment]
Only thing I'm worried about is the VCR cassette, I assume it's fully portable but let me know if it isn't.

**Comment by andrew** [comment]
Yeah that looks fine to me, travis seems to like it.

**Comment by andrew** [comment]
:tada:

**Pull request merged**
