### PR TITLE
add labels method to issue model. display issues on project show page

### LINKED ISSUE #25: Download active project issue labels
When we update a project, also download labels that are actively being used to help with filtering later.

### PR DESCRIPTION
**Pull request by wadtech**
also faraday wasn't actually caching properly, so now it is, otherwise
performance is dreadful for project#show

closes #25

### CODE REVIEW

**Comment by andrew** [comment]
Lovely work, I'll deploy this when I get home :+1:

**Comment by andrew** [comment]
@wadtech am I right in thinking I need to run a few rake tasks when I deploy this?

    rake db:migrate projects:refresh_issues

Also if you'd like me to add you to the heroku account so you can deploy, which email do you use for heroku?

**Comment by wadtech** [comment]
I forgot to mention that, yeah the rake task just captures the number field
which turns out is really important.

I don't think I have a heroku account (sacrilege!), I'll sort one out and
get back to you

**Comment by andrew** [comment]
Deploying it now, sorry for the delay! @wadtech I've also added you to the heroku app so you can deploy now :tada:

**Pull request merged**
