### PR TITLE
About page

### PR DESCRIPTION
**Pull request by wadtech**
Make a start on something for #17 

I'm painfully aware that it's a lot of text with no i18n support so that should probably be sorted out before merging.

I'm also totally open to having my copy rewritten by anybody that is interested. I'm not the best writer in the world.

### CODE REVIEW

**Comment by andrew** [comment]
Thank @wadtech, very nice!

**Comment by wadtech** [comment]
I'm going to add some specs and take care of the i18n bit before it's merge-worthy.

**Comment by andrew** [comment]
Yeah that would be great.

**Comment by killerog** [comment]
In the en.yml file some lines seem to miss double quotes, I don't know if that's required but might be nice to keep it consistent.
I would limit the "what is contribulator" paragraph to just the finding of projects. Rating is nice but not the primary goal, and it's also being described already further down. Although that could maybe be extended.
"Individual items are scored, with some being weighted higher than others". Shouldn't we say why or how they are weighted differently? Or maybe remove that bit altogether?

**Comment by wadtech** [comment]
Hey @killerog, thanks for your input.

I'll make your suggested changes and ping you here if you'd like to further proofread.

I agree it needs to be better structured. I actually don't know the rationale behind some of the score weightings which is why it's a bit vague.

On that note, if you or anybody wishes to write a paragraph about that it'd be very much appreciated.

**Comment by wadtech** [comment]
Hi @killerog, I've pushed some changes, would you like to give it another read?

**Comment by andrew** [comment]
Looks brilliant @wadtech, great work!

**Comment by wadtech** [comment]
Neat, I'll merge this if you're happy @andrew.

Welcome any further PRs against it if you're interested @killerog (or anybody!)

**Comment by andrew** [comment]
:shipit:

**Pull request merged**
