### PR TITLE
Add project form inline to the header instead of the link to projects/new.

### PR DESCRIPTION
**Pull request by wadtech**
I also shoved in the turbolinks loading bar thing, for my own sanity.

contrib

### CODE REVIEW

**Comment by wadtech** [comment]
The 'Add' button text could probably be changed to 'Search' since effectively it's "create or go to" in behaviour.

**Comment by andrew** [comment]
Nice work @wadtech, I don't mind removing turbolinks if it's causing you headaches.

**Comment by andrew** [comment]
@wadtech we should redirect to the /:owner/:name link after adding the page, and if it's already been added, show a flash message that it's already been added.

**Comment by wadtech** [comment]
Turbolinks are cool, but when it's slow with no progress indicator it's weird.

Good call on the redirect, I'll take a look

**Pull request merged**
