### PR TITLE
Prompt for confirmation on adding a project not already imported

### PR DESCRIPTION
**Pull request by wadtech**
adds confirm step relating to #49

### CODE REVIEW

**Comment by andrew** [comment]
Looking good, can you add a screenshot of the confirmation page?

**Comment by wadtech** [comment]
Certainly.

confirm

**Comment by wadtech** [comment]
'go back' in this case is a `window.history(-1)` thing

**Comment by andrew** [comment]
:+1: LGTM

**Comment by wadtech** [comment]
:ship:

**Pull request merged**
